// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCho8iDbwYzU9y8mBj3DrrSoNabTRuKcvM',
    appId: '1:888873107827:web:bc6329da0eaa029d3d4506',
    messagingSenderId: '888873107827',
    projectId: 'fir-tts-b8425',
    authDomain: 'fir-tts-b8425.firebaseapp.com',
    storageBucket: 'fir-tts-b8425.appspot.com',
    measurementId: 'G-B1Z7KY5TM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnaMBuV5zZ4z-F9lTX4ZYXfO8Bm05S02w',
    appId: '1:888873107827:android:839609f44a9994453d4506',
    messagingSenderId: '888873107827',
    projectId: 'fir-tts-b8425',
    storageBucket: 'fir-tts-b8425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDjxfr82oTsAbNpqfVPTWapW5yZEcjuNk',
    appId: '1:888873107827:ios:bff905df4345d7733d4506',
    messagingSenderId: '888873107827',
    projectId: 'fir-tts-b8425',
    storageBucket: 'fir-tts-b8425.appspot.com',
    iosBundleId: 'com.example.firebaseImgae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDjxfr82oTsAbNpqfVPTWapW5yZEcjuNk',
    appId: '1:888873107827:ios:368da6e4bdc4f15c3d4506',
    messagingSenderId: '888873107827',
    projectId: 'fir-tts-b8425',
    storageBucket: 'fir-tts-b8425.appspot.com',
    iosBundleId: 'com.example.firebaseImgae.RunnerTests',
  );
}
